/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        danilo: {
          bg: "#FFFFFF",
          "bg-secondary": "#F8FAFC",
          "bg-tertiary": "#F1F5F9",
          surface: "#FFFFFF",
          "surface-hover": "#F8FAFC",
          "surface-active": "#F1F5F9",
          "surface-elevated": "#FFFFFF",
          border: "#E2E8F0",
          "border-subtle": "#F1F5F9",
          "border-focus": "#2563EB",
          primary: "#2563EB",
          "primary-hover": "#1D4ED8",
          "primary-subtle": "rgba(37,99,235,0.08)",
          "primary-muted": "rgba(37,99,235,0.04)",
          secondary: "#0891B2",
          "secondary-hover": "#0E7490",
          "secondary-subtle": "rgba(8,145,178,0.08)",
          text: "#0F172A",
          "text-secondary": "#475569",
          "text-muted": "#94A3B8",
          "text-placeholder": "#CBD5E1",
          success: "#16A34A",
          "success-hover": "#15803D",
          "success-subtle": "rgba(22,163,74,0.08)",
          warning: "#D97706",
          "warning-subtle": "rgba(217,119,6,0.08)",
          error: "#DC2626",
          "error-subtle": "rgba(220,38,38,0.08)",
          purple: "#7C3AED",
          "purple-subtle": "rgba(124,58,237,0.08)",
          orange: "#EA580C",
          "orange-subtle": "rgba(234,88,12,0.08)",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "Fira Code", "Consolas", "monospace"],
      },
      fontSize: {
        "2xs": ["10px", "14px"],
        "3xl": ["1.75rem", "2.25rem"],
        "4xl": ["2.25rem", "2.75rem"],
      },
      borderRadius: {
        "2xl": "16px",
        "3xl": "20px",
        "4xl": "24px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.04)",
        sm: "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)",
        md: "0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.04)",
        lg: "0 10px 15px -3px rgb(0 0 0 / 0.06), 0 4px 6px -4px rgb(0 0 0 / 0.04)",
        xl: "0 20px 25px -5px rgb(0 0 0 / 0.06), 0 8px 10px -6px rgb(0 0 0 / 0.04)",
        glow: "0 0 24px rgba(37,99,235,0.12)",
        "glow-sm": "0 0 12px rgba(37,99,235,0.08)",
        "inner-sm": "inset 0 1px 2px rgba(0,0,0,0.04)",
        ring: "0 0 0 3px rgba(37,99,235,0.12)",
      },
      spacing: {
        13: "3.25rem",
        15: "3.75rem",
        18: "4.5rem",
        22: "5.5rem",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      animation: {
        "fade-in": "fadeIn 0.25s ease-out both",
        "fade-in-fast": "fadeIn 0.15s ease-out both",
        "slide-up": "slideUp 0.3s ease-out both",
        "slide-down": "slideDown 0.3s ease-out both",
        "slide-in-left": "slideInLeft 0.3s ease-out both",
        "slide-in-right": "slideInRight 0.3s ease-out both",
        pulse: "pulse 1.8s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "pulse-fast": "pulse 1.2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        spin: "spin 0.9s linear infinite",
        "bounce-dot": "bounceDot 1.2s ease-in-out infinite",
        shimmer: "shimmer 2s linear infinite",
        "scale-in": "scaleIn 0.2s ease-out both",
        float: "float 3s ease-in-out infinite",
        "typing-dot": "typingDot 1.4s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
        spin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        bounceDot: {
          "0%, 80%, 100%": { transform: "scale(0.8)", opacity: "0.5" },
          "40%": { transform: "scale(1.1)", opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        typingDot: {
          "0%, 80%, 100%": { transform: "scale(0.6)", opacity: "0.3" },
          "40%": { transform: "scale(1)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
